float speed = 0.01;
String game_name = "Chess Roll";
String used_cam;
float boxWidth = 50;
float boxHeight = 50;
float viewheight = 105;
float fov = PI/4;
float cylinderH = 5;
float cylinderR = 3;
float sphereR = 2;
float mu = 2;
int logPeriod = 4;